// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"WaitCommandUntilPromiseSettled","status":true,"description":"非同期処理が完了するまで、イベントコマンドを待機する機能を提供します","parameters":{}},
{"name":"AtsumaruApi","status":false,"description":"アツマールAPIを利用可能にするプラグインです","parameters":{"commentGposVerbose":"false","commentGposMode":"v3","commonOnComment":"","commentCommonOnComment":"","commandCommonOnComment":"","createdAtCommonOnComment":"","isPostCommonOnComment":"","isGiftCommonOnComment":"","nameCommonOnComment":"","pointCommonOnComment":"","thanksCommonOnComment":"","replyCommonOnComment":"","thanksSettings":"","autoThanks":"false","thanksText":"ありがとうございました！","thanksImage":"","clapThanksText":"ありがとうございます！","clapThanksImage":"","giftThanksText":"ありがとうございます！ゲーム制作の励みになります！","giftThanksImage":""}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。","parameters":{"GridSize":"48","TestMapId":"-1"}},
{"name":"AnotherNewGame","status":true,"description":"アナザーニューゲーム追加プラグイン","parameters":{"anotherDataList":"[\"{\\\"name\\\":\\\"エンディング一覧\\\",\\\"mapId\\\":\\\"17\\\",\\\"mapX\\\":\\\"1\\\",\\\"mapY\\\":\\\"1\\\",\\\"hidden\\\":\\\"false\\\",\\\"disable\\\":\\\"false\\\",\\\"addPosition\\\":\\\"3\\\",\\\"switchId\\\":\\\"0\\\",\\\"fileLoad\\\":\\\"false\\\",\\\"noFadeout\\\":\\\"false\\\"}\"]"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"PictureIdVariable":"0","InvalidSwitchId":"0","FlickDistance":"60","FlickTimeVariable":"0","FlickDegreeVariable":"0"}},
{"name":"UTA_CommonSaveMZ","status":true,"description":"セーブデータ間で共有のセーブデータを作成し、\n指定したスイッチ・変数の状態をセーブデータ間で共有します。","parameters":{"targetSwitches":"[\"15-23\"]","targetVariables":"[]","applyOnLoad":"true","applyOnSave":"true","applyOnNewGame":"true","applyOnAutoSave":"false","applyOnGameover":"true","saveFileName":"uta_common"}},
{"name":"TitleImageChange","status":true,"description":"タイトル画面変更プラグイン","parameters":{"StoryPhaseVariable":"1","PriorityVariable":"0","TitleList":"[\"{\\\"StoryPhaseCondition\\\":\\\"1\\\",\\\"TitleImage\\\":\\\"title2\\\",\\\"TitleBgm\\\":\\\"titleBGM\\\"}\"]"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"AlwaysDash":"true","CommandRemember":"false","TouchUi":"true","BgmVolume":"100","BgsVolume":"100","MeVolume":"100","SeVolume":"100","EraseAlwaysDash":"false","EraseCommandRemember":"false","EraseTouchUi":"false","EraseBgmVolume":"false","EraseBgsVolume":"false","EraseMeVolume":"false","EraseSeVolume":"false"}}
];
